fix: XApiProcessor.transform_event needs to handle lists of events
* fixes "AttributeError: 'list' object has no attribute 'to_json'"
  during event processing for one-to-many problem_check events
* adds test for ^
* reverts unneeded change to test_caliper to reinstate 100% test coverage